#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: eks-deploy
#spec:
#  replicas: 2
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 1
#      maxSurge: 1
#  selector:
#    matchLabels:
#      app: eks
#  template:
#    metadata:
#      labels:
#        app: eks
#    spec:
#      containers:
#      - name: hello-k8s
#        image: nginx
#        imagePullPolicy: Always
#        securityContext:
#          privileged: false
#          readOnlyRootFilesystem: true
#          allowPrivilegeEscalation: false
#        ports:
#        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2-guestsrv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy2-guestsrv
  template:
    metadata:
      labels:
        app: deploy2-guestsrv
    spec:
      containers:
      - name: deploy2-guestsrv
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy3-adminsrv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy3-adminsrv
  template:
    metadata:
      labels:
        app: deploy3-adminsrv
    spec:
      containers:
      - name: deploy3-adminsrv
        image: k8s.gcr.io/echoserver:1.5
        ports:
        - containerPort: 8080