apiVersion: v1
kind: Service
metadata:
  name: eks-svc
spec:
  ports:
  - port: 9001
    targetPort: 80
  selector:
    app: eks
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: svc2-guest
spec:
  ports:
    - name: guest-port
      port: 9002
      targetPort: 8080
  selector:
    app: guestsrv
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: svc3-admin
spec:
  ports:
    - name: admin-port
      port: 9003
      targetPort: 8080
  selector:
    app: adminsrv
  type: NodePort