
#apiVersion: v1
#kind: Service
#metadata:
#  name: eks-svc
#spec:
#  ports:
#  - port: 9001
#    targetPort: 8080
#  selector:
#    app: eks
#  type: NodePort
#
---
apiVersion: v1
kind: Service
metadata:
  name: ikuzo-web-front-svc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  ports:
    - name: ikuzo-web-front-port
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: ikuzo-web-front
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ikuzo-web-back-svc
spec:
  ports:
    - name: ikuzo-web-back-port
      port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app: ikuzo-web-back
  type: NodePort