#apiVersion: v1
#kind: Service
#metadata:
#  name: eks
#spec:
#  ports:
#  - port: 9001
#    targetPort: 8080
#  selector:
#    app: eks
#  type: NodePort
#
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: front
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: back
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/today/krw"
spec:
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app: back
  type: NodePort