#
#apiVersion: v1
#kind: Service
#metadata:
#  name: eks-svc
#spec:
#  ports:
#  - port: 9001
#    targetPort: 8080
#  selector:
#    app: eks
#  type: NodePort
#
---
apiVersion: v1
kind: Service
metadata:
  name: ikuzoWeb-svc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: ["/guest/aws"]
spec:
  ports:
    - name: ikuzoWeb-port
      port: 3000
      targetPort: 8080
  selector:
    app: ikuzoWeb
  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: deploy3-adminsrv
#  annotations:
#    alb.ingress.kubernetes.io/healthcheck-path: "/admin/all"
#spec:
#  ports:
#    - name: deploy3-adminsrv
#      port: 9003
#      targetPort: 8080
#  selector:
#    app: deploy3-adminsrv
#  type: NodePort