#
#apiVersion: v1
#kind: Service
#metadata:
#  name: eks-svc
#spec:
#  ports:
#  - port: 9001
#    targetPort: 8080
#  selector:
#    app: eks
#  type: NodePort
#
---
apiVersion: v1
kind: Service
metadata:
  name: ikuzoWebFront_SVC
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: ["/guest/aws"]
spec:
  ports:
    - name: ikuzoWebFront_Port
      port: 9002
      targetPort: 3000
  selector:
    app: ikuzoWeb
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ikuzoWebBack_SVC
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/admin/all"
spec:
  ports:
    - name: ikuzoWebBack_Port
      port: 9003
      targetPort: 3100
  selector:
    app: ikuzoWebBack
  type: NodePort